# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
dist: trusty

language: python
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .

env:
  - CI_TARGET=core
  - CI_TARGET=iverilog
  - CI_TARGET=ghdl

before_script:
  - if [[ "$CI_TARGET" == "iverilog" ]]; then
      sudo apt-get -qq update;
      sudo apt-get install iverilog;
    elif [[ "$CI_TARGET" == "ghdl" ]]; then
      wget -O ghdl.tgz "https://github.com/ghdl/ghdl/releases/download/v0.35/ghdl-0.35-mcode-ubuntu14.tgz";
      mkdir -p ghdl;
      tar -xvzf ghdl.tgz -C ghdl/;
      export PATH=$PATH:$PWD/ghdl/bin;
    fi

script: ./scripts/ci.sh

notifications:
  email: false
